// Generated by Wrangler on Wed May 22 2024 12:07:34 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types`

interface Env {
	CF_ENV: string;
	SERVER_ORIGIN: string;
	RP_NAME: string;
	RP_ID: string;
	DB: D1Database;
}
