#:schema node_modules/wrangler/config-schema.json

name = "remix-example-passkey-auth"
compatibility_date = "2024-05-22"
upload_source_maps = true

[env.production.vars]
SERVER_ORIGIN = "https://remix-example-passkey-auth.hoishin.dev"
RP_NAME = "Remix Example Passkey Auth"
RP_ID = "remix-example-passkey-auth.hoishin.dev"

[[d1_databases]]
binding = "DB"
database_name = "remix-example-passkey-auth"
database_id = "548dc3c5-15b1-44f2-908e-72931e38b8b5"
